name: Hexo

# 触发条件：push 到 hexo 分支后触发
on:
  push:
    branches:
      - hexo

env:
  TZ: Asia/Shanghai
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install Hexo dependencies
        run: |
          npm install -g hexo-cli

          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

          npm install hexo-blog-encrypt

      - name: Generate files
        run: |
          hexo clean
          hexo generate

      - name: Deploy Hexo blog
        run: |
          cd ./public

          git init -b master
          git config user.name "coldwave96"
          git config user.email "676803965@qq.com"

          echo "blog.110910.xyz" > CNAME
          echo "# Hexo" > README.md
          echo "Personal Blog" >> README.md
          touch .nojekyll

          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"

          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Coldwave96/Coldwave96.github.io.git"
          git push --force --quiet origin master
